apiVersion: v1
kind: ReplicationController
metadata:
  name: example-service1-rc
spec:
  replicas: 1
  selector:
    app: example-service1
  template:
    metadata:
      labels:
        app: example-service1
    spec:
      containers:
      - name: example-service1
        image: soloio/example-service1:v0.2.0
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: HOST_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
kind: Service
apiVersion: v1
metadata:
  name: example-service1-svc
spec:
  selector:
    app: example-service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080